# Generated by Django 4.2.7 on 2023-11-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('male', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский'), ('M', 'Другой')], max_length=1)),
                ('start_rental', models.DateTimeField(auto_now_add=True)),
                ('end_rental', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
