# Generated by Django 4.2.7 on 2023-11-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentCar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentcar',
            name='male',
            field=models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1),
        ),
    ]
