# Generated by Django 4.2.7 on 2023-11-23 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RentCar', '0002_alter_rentcar_male'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('marka', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('seating_capacity', models.PositiveIntegerField()),
                ('four_wheel_drive', models.BooleanField(default=True)),
                ('ground_clearance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('off_road', models.CharField(max_length=100)),
                ('additional_features', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='rentcar',
            name='select_car',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='RentCar.cars'),
            preserve_default=False,
        ),
    ]
