# Generated by Django 4.2.7 on 2023-11-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PixelPulse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
