# Generated by Django 4.2.7 on 2023-11-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PixelPulse', '0002_alter_tourlist_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
            ],
        ),
    ]
