# Generated by Django 4.2.7 on 2023-11-23 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PixelPulse', '0005_alter_review_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTourRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('telegram_id', models.CharField(blank=True, max_length=100, null=True)),
                ('destinations', models.TextField()),
                ('number_of_people', models.PositiveIntegerField()),
                ('number_of_days', models.PositiveIntegerField()),
                ('meal_option', models.CharField(choices=[('BB', 'Завтрак'), ('BB+L', 'Завтрак и обед'), ('BB+L+D', 'Завтрак, обед и ужин')], max_length=20)),
                ('accommodation_option', models.CharField(choices=[('2', 'Двухзвездочный отель'), ('3', 'Трехзвездочный отель'), ('4', 'Четырехзвездочный отель'), ('5', 'Пятизвездочный отель'), ('guesthouse', 'Гостевой дом')], max_length=20)),
                ('transportation_option', models.CharField(choices=[('driver_car', 'Водитель + авто'), ('guide_driver_car', 'Гид + водитель + авто'), ('rent_car', 'Аренда машины')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='PixelPulse.tourlist'),
        ),
    ]
