# Generated by Django 4.2.7 on 2023-11-27 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PixelPulse', '0008_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
